Repository GSG-G13/CC-project, pull requests merged in 2023-03, with the labels that each got.

#3 Finish structure of project relate#2
  .gitignore
  index.html
  package-lock.json
  package.json
  script.test.js
  script/api1.js
  script/api2.js
  style.css
Labels: inProgress

#4 General Layout
  .gitignore
  index.html
  style.css
Labels: Done

#6 html css js files update for converter section
  CSS/darkstyle.css
  CSS/style.css
  index.html
  script/api1.js
  style.css
Labels: awaiting

#8 update style and add another function to return usd amount
  CSS/darkstyle.css
  CSS/style.css
  index.html
  script/api1.js
Labels: Done

#10 css update and logo addition
  CSS/darkstyle.css
  CSS/style.css
  index.html
Labels: awaiting

#13 12 crypto
  CSS/darkstyle.css
  CSS/style.css
  index.html
  script/api1.js
  script/api2.js
  style.css
Labels: awaiting

#11 readme file
  README.md
Labels: Done

#15 fix css relate#14
  style.css
Labels: awaiting

#16 Finish
  script.test.js
  script/api1.js
  style.css
Labels: awaiting
